<?php

$dictionary['Account']['fields']['image'] = array (
    'required' => false,
    'name' => 'image',
    'vname' => 'LBL_IMAGE',
    'type' => 'image',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => true,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 255,
    'size' => '20',
    'studio' => 'visible',
    'dbType' => 'varchar',
    'border' => '',
    'width' => '120',
    'height' => '',
);

$dictionary['Account']['fields']['recommendations'] = array (
    'name' => 'recommendations',
    'vname' => 'LBL_RECOMMENDATIONS',
    'type' => 'int',
    'readonly' => true,
    'len' => 11,
    'required' => true,
    'unified_search' => true,
    'duplicate_merge' => 'disabled',
    'disable_num_format' => true,
    'readonly' => true,
    'enforeced' => true,
);

$dictionary['Account']['fields']['terms_and_conditions'] = array (
    'name' => 'terms_and_conditions',
    'vname' => 'LBL_TERMS_AND_CONDITIONS',
    'type' => 'text',
    'comment' => 'Full text of the note',
    'rows' => '6',
    'cols' => '80',
    'required' => false,
    'massupdate' => 0,
    'no_default' => false,
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
);

$dictionary['Account']['fields']['instangram_url'] = array (
    'required' => false,
    'name' => 'instangram_url',
    'vname' => 'LBL_INSTANGRAM_URL',
    'type' => 'url',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'dbType' => 'varchar',
    'gen' => '',
    'link_target' => '_self',
);